question_data = [
    {"text": "In Python, the GIL allows multiple native threads to execute Python bytecode simultaneously.", "answer": "False"},
    {"text": "In SQL, a LEFT JOIN returns all records from the left table even if there is no match in the right table.", "answer": "True"},
    {"text": "Normalization in databases is primarily used to reduce redundancy and improve data integrity.", "answer": "True"},
    {"text": "In OOP, polymorphism allows methods to have the same name but different implementations.", "answer": "True"},
    {"text": "In machine learning, L2 regularization adds the absolute values of weights to the loss function.", "answer": "False"},
    {"text": "A binary search tree always guarantees O(log n) search time.", "answer": "False"},
    {"text": "In operating systems, a context switch occurs when the CPU switches from one process to another.", "answer": "True"},
    {"text": "TCP is a connectionless protocol that does not guarantee delivery.", "answer": "False"},
    {"text": "In Java, the 'final' keyword can be applied to classes, methods, and variables.", "answer": "True"},
    {"text": "A hash function must always return unique outputs for different inputs.", "answer": "False"},
    {"text": "In REST APIs, PUT is generally used to update an entire resource.", "answer": "True"},
    {"text": "Time complexity of Heap Sort in the worst case is O(n log n).", "answer": "True"},
    {"text": "Deadlock can occur only if all four Coffman conditions hold simultaneously.", "answer": "True"},
    {"text": "In cloud computing, horizontal scaling refers to increasing CPU cores or RAM of a single machine.", "answer": "False"},
    {"text": "A subnet mask determines how many hosts can exist within a network segment.", "answer": "True"},
    {"text": "In Git, a detached HEAD state means the repository has no commits.", "answer": "False"},
    {"text": "In Python, tuples are mutable while lists are immutable.", "answer": "False"},
    {"text": "Gradient Descent always converges to the global minimum regardless of the function shape.", "answer": "False"},
    {"text": "In computer architecture, cache memory is faster than RAM.", "answer": "True"},
    {"text": "Load balancing distributes incoming traffic across multiple servers to improve availability.", "answer": "True"},
]
