persons = [
    {
        'name': 'Virat Kohli',
        'follower_count': 265,
        'description': 'Cricketer and former Indian captain',
        'country': 'India',
    },
    {
        'name': 'Narendra Modi',
        'follower_count': 220,
        'description': 'Prime Minister of India',
        'country': 'India',
    },
    {
        'name': 'Priyanka Chopra Jonas',
        'follower_count': 90,
        'description': 'Actress and Global Icon',
        'country': 'India',
    },
    {
        'name': 'Shah Rukh Khan',
        'follower_count': 45,
        'description': 'Actor and Film Producer',
        'country': 'India',
    },
    {
        'name': 'Alia Bhatt',
        'follower_count': 85,
        'description': 'Actress and Singer',
        'country': 'India',
    },
    {
        'name': 'MS Dhoni',
        'follower_count': 50,
        'description': 'Former Indian Cricket Captain',
        'country': 'India',
    },
    {
        'name': 'Deepika Padukone',
        'follower_count': 80,
        'description': 'Actress and Producer',
        'country': 'India',
    },
    {
        'name': 'Ratan Tata',
        'follower_count': 15,
        'description': 'Industrialist and Philanthropist',
        'country': 'India',
    },
    {
        'name': 'Sachin Tendulkar',
        'follower_count': 45,
        'description': 'Legendary Cricketer',
        'country': 'India',
    },
    {
        'name': 'Amitabh Bachchan',
        'follower_count': 35,
        'description': 'Actor and Television Host',
        'country': 'India',
    },
    {
        'name': 'Akshay Kumar',
        'follower_count': 70,
        'description': 'Actor and Philanthropist',
        'country': 'India',
    },
    {
        'name': 'Katrina Kaif',
        'follower_count': 75,
        'description': 'Actress and Entrepreneur',
        'country': 'India',
    },
    {
        'name': 'Neeraj Chopra',
        'follower_count': 12,
        'description': 'Olympic Gold Medalist in Javelin Throw',
        'country': 'India',
    },
    {
        'name': 'Sundar Pichai',
        'follower_count': 8,
        'description': 'CEO of Google and Alphabet',
        'country': 'India',
    },
    {
        'name': 'A. R. Rahman',
        'follower_count': 20,
        'description': 'Composer and Musician',
        'country': 'India',
    },
    {
        'name': 'PV Sindhu',
        'follower_count': 10,
        'description': 'Olympic Badminton Player',
        'country': 'India',
    },
    {
        'name': 'Anushka Sharma',
        'follower_count': 70,
        'description': 'Actress and Producer',
        'country': 'India',
    },
    {
        'name': 'Karan Johar',
        'follower_count': 22,
        'description': 'Film Director and Producer',
        'country': 'India',
    },
    {
        'name': 'Mukesh Ambani',
        'follower_count': 5,
        'description': 'Business Magnate, Reliance Industries',
        'country': 'India',
    },
    {
        'name': 'Gautam Adani',
        'follower_count': 3,
        'description': 'Industrialist and Entrepreneur',
        'country': 'India',
    },
    {
        'name': 'Hrithik Roshan',
        'follower_count': 55,
        'description': 'Actor and Dancer',
        'country': 'India',
    },
    {
        'name': 'Ranveer Singh',
        'follower_count': 45,
        'description': 'Actor and Performer',
        'country': 'India',
    },
    {
        'name': 'Rohit Sharma',
        'follower_count': 35,
        'description': 'Cricketer and Indian Captain',
        'country': 'India',
    },
    {
        'name': 'KL Rahul',
        'follower_count': 20,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Kareena Kapoor Khan',
        'follower_count': 60,
        'description': 'Actress and Fashion Icon',
        'country': 'India',
    },
    {
        'name': 'Sania Mirza',
        'follower_count': 12,
        'description': 'Tennis Player',
        'country': 'India',
    },
    {
        'name': 'Rajinikanth',
        'follower_count': 15,
        'description': 'Actor and Cultural Icon',
        'country': 'India',
    },
    {
        'name': 'APJ Abdul Kalam',
        'follower_count': 18,
        'description': 'Former President and Scientist',
        'country': 'India',
    },
    {
        'name': 'Lata Mangeshkar',
        'follower_count': 25,
        'description': 'Legendary Playback Singer',
        'country': 'India',
    },
    {
        'name': 'Sonu Sood',
        'follower_count': 25,
        'description': 'Actor and Philanthropist',
        'country': 'India',
    },
{
        'name': 'Shraddha Kapoor',
        'follower_count': 94,
        'description': 'Actress',
        'country': 'India',
    },
    {
        'name': 'Salman Khan',
        'follower_count': 72,
        'description': 'Actor and Producer',
        'country': 'India',
    },
    {
        'name': 'Urvashi Rautela',
        'follower_count': 70,
        'description': 'Actress and Model',
        'country': 'India',
    },
    {
        'name': 'Neha Kakkar',
        'follower_count': 78,
        'description': 'Singer',
        'country': 'India',
    },
    {
        'name': 'Jacqueline Fernandez',
        'follower_count': 67,
        'description': 'Actress and Model',
        'country': 'India',
    },
    {
        'name': 'Disha Patani',
        'follower_count': 61,
        'description': 'Actress and Fitness Icon',
        'country': 'India',
    },
    {
        'name': 'Kriti Sanon',
        'follower_count': 58,
        'description': 'Actress',
        'country': 'India',
    },
    {
        'name': 'Sunny Leone',
        'follower_count': 56,
        'description': 'Actress and Entrepreneur',
        'country': 'India',
    },
    {
        'name': 'Shahid Kapoor',
        'follower_count': 48,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'name': 'Rohit Sharma',
        'follower_count': 35,
        'description': 'Cricketer and Indian Captain',
        'country': 'India',
    },
    {
        'name': 'KL Rahul',
        'follower_count': 20,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Sania Mirza',
        'follower_count': 12,
        'description': 'Tennis Player',
        'country': 'India',
    },
    {
        'name': 'Rajinikanth',
        'follower_count': 15,
        'description': 'Actor and Cultural Icon',
        'country': 'India',
    },
    {
        'name': 'APJ Abdul Kalam',
        'follower_count': 18,
        'description': 'Former President and Scientist',
        'country': 'India',
    },
    {
        'name': 'Lata Mangeshkar',
        'follower_count': 25,
        'description': 'Legendary Playback Singer',
        'country': 'India',
    },
    {
        'name': 'Sonu Sood',
        'follower_count': 25,
        'description': 'Actor and Philanthropist',
        'country': 'India',
    },
    {
        'name': 'Anushka Sharma',
        'follower_count': 69,
        'description': 'Actress and Producer',
        'country': 'India',
    },
    {
        'name': 'Karan Johar',
        'follower_count': 22,
        'description': 'Film Director and Producer',
        'country': 'India',
    },
    {
        'name': 'Mukesh Ambani',
        'follower_count': 5,
        'description': 'Business Magnate, Reliance Industries',
        'country': 'India',
    },
    {
        'name': 'Gautam Adani',
        'follower_count': 3,
        'description': 'Industrialist and Entrepreneur',
        'country': 'India',
    },
    {
        'name': 'Rhea Chakraborty',
        'follower_count': 14,
        'description': 'Actress and Model',
        'country': 'India',
    },
    {
        'name': 'Vijay Deverakonda',
        'follower_count': 34,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'name': 'Kamala Harris',
        'follower_count': 60,
        'description': 'Vice President of the United States (Indian-heritage)',
        'country': 'United States',
    },
    {
        'name': 'Arjun Kapoor',
        'follower_count': 30,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'name': 'Shruti Hassan',
        'follower_count': 16,
        'description': 'Actress and Singer',
        'country': 'India',
    },
    {
        'name': 'Sushmita Sen',
        'follower_count': 10,
        'description': 'Actress and Former Miss Universe',
        'country': 'India',
    },
    {
        'name': 'Irrfan Khan',
        'follower_count': 9,
        'description': 'Actor (late-legend)',
        'country': 'India',
    },
    {
        'name': 'Mammootty',
        'follower_count': 13,
        'description': 'Actor (Malayalam cinema)',
        'country': 'India',
    },
    {
        'name': 'Dilip Kumar',
        'follower_count': 8,
        'description': 'Legendary Actor',
        'country': 'India',
    },
    {
        'name': 'M.S. Swaminathan',
        'follower_count': 4,
        'description': 'Agricultural Scientist and Father of Green Revolution',
        'country': 'India',
    },
    {
        'name': 'Arundhati Roy',
        'follower_count': 6,
        'description': 'Author and Activist',
        'country': 'India',
    },
    {
        'name': 'Amartya Sen',
        'follower_count': 7,
        'description': 'Economist and Nobel Laureate',
        'country': 'India',
    },
    {
        'name': 'Sunil Gavaskar',
        'follower_count': 11,
        'description': 'Cricketer (legend)',
        'country': 'India',
    },
    {
        'name': 'Ravichandran Ashwin',
        'follower_count': 14,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Pankaj Tripathi',
        'follower_count': 18,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'name': 'Naseeruddin Shah',
        'follower_count': 9,
        'description': 'Veteran Actor',
        'country': 'India',
    },
    {
        'name': 'Bajrang Punia',
        'follower_count': 8,
        'description': 'Wrestler and Olympian',
        'country': 'India',
    },
    {
        'name': 'Kriti Kharbanda',
        'follower_count': 15,
        'description': 'Actress',
        'country': 'India',
    },
    {
        'name': 'Randeep Hooda',
        'follower_count': 12,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'name': 'Kuldeep Yadav',
        'follower_count': 10,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Shraddha Srinath',
        'follower_count': 6,
        'description': 'Actress (regional cinema)',
        'country': 'India',
    },
    {
        'name': 'Becoming Nikita',
        'follower_count': 5,
        'description': 'YouTuber & Chef',
        'country': 'India',
    },
    {
        'name': 'Kushaan Kamboj',
        'follower_count': 4,
        'description': 'Fitness Influencer',
        'country': 'India',
    },
    {
        'name': 'Anupam Kher',
        'follower_count': 23,
        'description': 'Actor and Thought-Leader',
        'country': 'India',
    },
    {
        'name': 'Sunny Deol',
        'follower_count': 19,
        'description': 'Actor and Politician',
        'country': 'India',
    },
    {
        'name': 'Zoya Akhtar',
        'follower_count': 8,
        'description': 'Film Director and Screenwriter',
        'country': 'India',
    },
    {
        'name': 'Farhan Akhtar',
        'follower_count': 32,
        'description': 'Actor, Director and Producer',
        'country': 'India',
    },
    {
        'name': 'Karan Johar (duplicate)',
        'follower_count': 22,
        'description': 'Film Director and Producer',
        'country': 'India',
    },
{
        'name': 'Allu Arjun',
        'follower_count': 90,
        'description': 'Actor and Dancer (Telugu Cinema)',
        'country': 'India',
    },
    {
        'name': 'Ram Charan',
        'follower_count': 80,
        'description': 'Actor and Producer (Telugu Cinema)',
        'country': 'India',
    },
    {
        'name': 'N. T. Rama Rao Jr.',
        'follower_count': 50,
        'description': 'Actor (Tollywood)',
        'country': 'India',
    },
    {
        'name': 'Mahesh Babu',
        'follower_count': 45,
        'description': 'Actor (Telugu Cinema)',
        'country': 'India',
    },
    {
        'name': 'Yash',
        'follower_count': 30,
        'description': 'Actor (Kannada Cinema, KGF fame)',
        'country': 'India',
    },
    {
        'name': 'Vijay Thalapathy',
        'follower_count': 55,
        'description': 'Actor (Tamil Cinema)',
        'country': 'India',
    },
    {
        'name': 'Samantha Ruth Prabhu',
        'follower_count': 35,
        'description': 'Actress (Telugu and Tamil Cinema)',
        'country': 'India',
    },
    {
        'name': 'Nayanthara',
        'follower_count': 25,
        'description': 'Actress and Producer (Tamil Cinema)',
        'country': 'India',
    },
    {
        'name': 'Ajay Devgn',
        'follower_count': 35,
        'description': 'Actor, Director and Producer',
        'country': 'India',
    },
    {
        'name': 'Ranbir Kapoor',
        'follower_count': 40,
        'description': 'Actor and Producer',
        'country': 'India',
    },
    {
        'name': 'Kiara Advani',
        'follower_count': 60,
        'description': 'Actress and Model',
        'country': 'India',
    },
    {
        'name': 'Sara Ali Khan',
        'follower_count': 50,
        'description': 'Actress',
        'country': 'India',
    },
    {
        'name': 'Tara Sutaria',
        'follower_count': 40,
        'description': 'Actress and Singer',
        'country': 'India',
    },
    {
        'name': 'Janhvi Kapoor',
        'follower_count': 50,
        'description': 'Actress and Model',
        'country': 'India',
    },
    {
        'name': 'Rashmika Mandanna',
        'follower_count': 45,
        'description': 'Actress (Pan-India star)',
        'country': 'India',
    },
    {
        'name': 'Kangana Ranaut',
        'follower_count': 10,
        'description': 'Actress and Producer',
        'country': 'India',
    },
    {
        'name': 'Sonam Kapoor Ahuja',
        'follower_count': 35,
        'description': 'Actress and Fashion Entrepreneur',
        'country': 'India',
    },
    {
        'name': 'Bhumi Pednekar',
        'follower_count': 20,
        'description': 'Actress and Environmental Activist',
        'country': 'India',
    },
    {
        'name': 'Sushant Singh Rajput',
        'follower_count': 25,
        'description': 'Actor (Late)',
        'country': 'India',
    },
    {
        'name': 'Kapil Sharma',
        'follower_count': 45,
        'description': 'Comedian and TV Host',
        'country': 'India',
    },
    {
        'name': 'Ravindra Jadeja',
        'follower_count': 20,
        'description': 'Cricketer and All-Rounder',
        'country': 'India',
    },
    {
        'name': 'Hardik Pandya',
        'follower_count': 30,
        'description': 'Cricketer and All-Rounder',
        'country': 'India',
    },
    {
        'name': 'Shubman Gill',
        'follower_count': 18,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Smriti Mandhana',
        'follower_count': 12,
        'description': 'Women’s Cricketer and Vice Captain',
        'country': 'India',
    },
    {
        'name': 'Mary Kom',
        'follower_count': 10,
        'description': 'Boxer and Olympic Medalist',
        'country': 'India',
    },
    {
        'name': 'Hima Das',
        'follower_count': 7,
        'description': 'Sprinter and Athlete',
        'country': 'India',
    },
    {
        'name': 'Vikram Sarabhai',
        'follower_count': 3,
        'description': 'Scientist and Founder of ISRO',
        'country': 'India',
    },
    {
        'name': 'Dr. Manmohan Singh',
        'follower_count': 5,
        'description': 'Former Prime Minister and Economist',
        'country': 'India',
    },
    {
        'name': 'Kiran Bedi',
        'follower_count': 6,
        'description': 'Retired IPS Officer and Politician',
        'country': 'India',
    },
    {
        'name': 'Azim Premji',
        'follower_count': 4,
        'description': 'Business Tycoon and Philanthropist (Wipro)',
        'country': 'India',
    }
]
